[package]
name = "coder-api-gen"
version = "0.0.0"
edition.workspace = true
publish.workspace = true
description = "Unofficial generated client for the Coder API. Not supported by Coder."

[dependencies]
chrono.workspace = true
futures.workspace = true
progenitor-client.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
