[package]
name = "coder-sdk"
version = "0.0.0"
edition.workspace = true
publish.workspace = true
description = "Unofficial hand-written layer over coder-api-gen. Not supported by Coder."

[dependencies]
base64.workspace = true
coder-api-gen = { path = "../coder-api-gen" }
futures.workspace = true
progenitor-client.workspace = true
reqwest.workspace = true
reqwest-websocket.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio-tungstenite.workspace = true
wiremock.workspace = true
