//! Unofficial client for the Coder API, generated by progenitor from coder/coder's Swagger spec.
//!
//! Do not edit `generated.rs`; run `scripts/regenerate.sh` instead.
#![allow(clippy::all, clippy::pedantic, missing_docs, unused_imports, dead_code)]

include!("generated.rs");
