use std::{env, fs, process::ExitCode};

fn render(spec: serde_json::Value, source: &str) -> Result<String, String> {
    let spec = serde_json::from_value(spec).map_err(|e| format!("parse spec: {e}"))?;
    let mut generator = progenitor::Generator::default();
    let tokens = generator
        .generate_tokens(&spec)
        .map_err(|e| format!("generate: {e:?}"))?;
    let file = syn::parse2(tokens).map_err(|e| format!("parse tokens: {e}"))?;
    Ok(format!(
        "// @generated by cargo xtask generate from coder/coder {source}. Do not edit.\n{}",
        prettyplease::unparse(&file)
    ))
}

fn main() -> ExitCode {
    let args: Vec<String> = env::args().skip(1).collect();
    let [command, spec_path, out_path, ref_path] = args.as_slice() else {
        eprintln!("usage: cargo xtask generate <patched-spec> <out-file> <ref-file>");
        return ExitCode::from(2);
    };
    if command != "generate" {
        eprintln!("unknown command {command}");
        return ExitCode::from(2);
    }
    let run = || -> Result<(), String> {
        let spec: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(spec_path).map_err(|e| e.to_string())?)
                .map_err(|e| e.to_string())?;
        let source = fs::read_to_string(ref_path).map_err(|e| e.to_string())?;
        let code = render(spec, source.trim())?;
        fs::write(out_path, code).map_err(|e| e.to_string())
    };
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("{e}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::render;

    #[test]
    fn renders_a_minimal_spec_with_header() {
        let spec = serde_json::json!({
            "openapi": "3.0.0",
            "info": {"title": "t", "version": "1"},
            "paths": {"/api/v2/buildinfo": {"get": {
                "operationId": "build-info",
                "responses": {"200": {"description": "OK", "content": {"application/json": {
                    "schema": {"type": "object", "properties": {"version": {"type": "string"}}}
                }}}}
            }}}
        });
        let code = render(spec, "v0.0.0 (abc123)").expect("render");
        assert!(code.starts_with(
            "// @generated by cargo xtask generate from coder/coder v0.0.0 (abc123). Do not edit.\n"
        ));
        assert!(code.contains("pub async fn build_info"));
    }
}
